### ISSUE TITLE
Ampcontrol

### ISSUE THREAD

**Issue by evilhf** [WiseLord/ampcontrol#1]
hello WiseLord , fine.
I am a lover of electronics and domino well .
however in the area of ​​programming 'm noob .
really liked your project and would like to ride in my amp .
but I have some doubts :
to compile all files in a single hex that will be sent to atmega32 through the recorder.
the files generated alert by ampcontroleditor and matrixclockeditor replaces the bin file, and how to include in the programming atmega32 ?
what program you use to include these files and generate the final file .hex to burn the atmega32 ?
sorry my doubts but I would love to understand this process.
congratulations on your project ..
as soon as possible please respondame

**Comment by WiseLord** [comment]
You can find Makefile in sources, which is used to compile sources.
So all you need is 1) make utility (100% sure it's preinstalled in any linux distribution) and 2) avr-gcc compiler (can be installed from package system).
To compile project for KS0108A display just type "make", or, for ST7920, "make DISPLAY=ST7920" in terminal window.
If you suddenly use Windows, you can install WinAVR program which includes both make, avr-gcc and other stuff.
Also, I periodically leave fresh builds in radiokot.ru forum. Here is the latest build: http://radiokot.ru/forum/viewtopic.php?p=2613216#p2613216

**Comment by WiseLord** [comment]
To run the project you should flash into ATmega32 both hex (flash part) and bin (eeprom part) files. You can use avrdude flasher or any other you like. Makefile includes targets to do it with avrdude ("make flash" and "make eeprom_xx").
To put it simply, .hex - is a firmware, .bin - is a settings file. Ampcontroleditor is just a helper utility which allows to edit theese settings. Matrixclockeditor is the same thing for my other project, matrixclock and can't be used for ampcontrol.
