### ISSUE TITLE
Настройки в виде меню

### ISSUE THREAD

**Issue by pirat777knj** [WiseLord/ampcontrol#2]
Хотелось бы видеть более расширенные настройки.
Предлагаю для настроек всего и вся использовать отдельную кнопку "меню", 
и внутри менюшку. Структура вложена в файле.
[Структура меню.pdf](https://github.com/WiseLord/ampcontrol/files/640068/default.pdf)

Ну и естественно оставить кнопку быстрых настроек аудио.

**Comment by pirat777knj** [comment]
Извиняюсь. Писал с телефона. Не знаю что с форматирование. Дома попробую поправить

**Comment by WiseLord** [comment]
Непонятна структура такого меню, как оно должно выглядеть, и как им управлять.

**Comment by pirat777knj** [comment]
Сделал в файле. Должно быть понятно.
Также есть еще одно пожелание.
При регулировке громкости сделайте, пожалуйста, отображение единицами в плюс.
А то регулировка сбивает с толку. Домочадцы уже весь мозг проели вопросом: почему так?
А вот в предусилителе, думаю, будет толково оставить регулировку в минус.

**Comment by pirat777knj** [comment]
Спешу сообщить - оформил, чтобы было понятно.
Вы просто молодец. Хорошая у Вас родилась мысль и Вы её развиваете.


2016-12-08 14:06 GMT+03:00 WiseLord <notifications@github.com>:

**Comment by WiseLord** [comment]
Такая структура меню и настроек звука (отдельный набор тембров и т.д. для каждого входа) полностью несовместима с текущим кодом. Возможно. в другом проекте что-то подобное и будет.

Показания при регулировках полностью соответстауют даташитам на аудиопроцессоры и здравому смыслу. Менять их на "попугаи" от нуля до N нет никакого смысла.

По поводу регулировки контраста хотелось бы узнать, как это физически должно происходить.

Ну и хотелось бы увидеть, как в подобном меню должно реализовываться управление кнопками.

**Comment by pirat777knj** [comment]
Эм... То есть как физически должена происходить регулировка контраста? Он
же сделана. У меня через пять минут контраст падает. И обратно
восстанавливается только когда выключишь. Или начнешь яркость регулировать.
В остальных случаях он не возвращается обратно.
Неужели это где то косяк? 0_о

Навигация..... Нажатие на энкодер - вход, скажем 3я кнопка - назад,
вращение энкодера - пролистывание. Как на 3д принтерах сделано. Там один
энкодер. А меню огроменное!

А в каком другом проекте вы будете это реализовывать?

**Comment by WiseLord** [comment]
Контраст постоянен и задаётся только подстроечными резисторами. Если он меняется во время работы - ничего кроме плавающего напряжения питания на ум не приходит.

Другой проект - что-то похожее, но например, на STM32.

**Comment by pirat777knj** [comment]
С этим буду разбираться. До мя доперло, что что-то не так.

**Comment by pirat777knj** [comment]
Добрый день. Вижу вас совсем не интересует предложенный мной функционал.
Несмотря на то, что промышленные ресиверы им обладают.
Как вы уже догадались - то я купил вашу плату в виде конструктора.
Не буду капать на мозги обратной связью с разработчиком и прочим. На этом
форуме все равно никогда не прислушиваются и почему-то считают всё бредом.
Сделаем проще. Вас устроит цена в 500 рублей за пару строк кода?

8 дек. 2016 г. 20:58 пользователь "Ратибор Конжин" <pirat777knj@gmail.com>
написал:

**Comment by Arik333** [comment]
Прошу добавить поддержку синтезатора LC72131.
