### ISSUE TITLE
Ошибка при компиляции, в чём причина подскажите

### ISSUE THREAD

**Issue by freecheng01** [WiseLord/ampcontrol#4]
C:\ampcontrol-m32-20170109\fft.c:38: ошибка: 'sinTable' is static but used in inline function 'sinTbl' which is not static [-Werror]
  ret = pgm_read_byte(&sinTable[phi & 0x1F]);
                       ^

**Comment by WiseLord** [comment]
Причина указана в сообщении об ошибке. Берите или компилятор подревнее (<5.0) или исходники поновее, где это уже поправлено https://github.com/WiseLord/ampcontrol/commit/c34a5e0815c25a95a042597a09573819a85a126e

**Comment by freecheng01** [comment]
Спасибо, немного уже разобрался , взял 5c041ba всё проходит. Ещё вопрос - для корпуса dip40 изменений в программе не требуется? Разводку печатки переделаю под себя.

**Comment by WiseLord** [comment]
Нет, главное, чтобы функционально те же ножки (пусть и с другой нумерацией) были использованы на тех же местах. Кстати, на форуме радиокота, где-то на первых страницах ветки, плата под DIP40 корпус выкладывалась.

**Comment by freecheng01** [comment]
Здорово, сейчас поищу. Ещё раз спасибо за проект, сам я пытался на 328 сделать но не осилил, знаний маловато и опыта, а Ваш проект зацепил, особенно в плане прорисовки экрана из ОЗУ. Буду его использовать как обучалку.

**Comment by WiseLord** [comment]
Собственно, ветка кода под m328 в проекте тоже имеется.
